Repository MBRjun/MBRjun-Blog, pull requests merged in 2023-02, with the labels that each got.

#16 Friend link
  source/links/index.md
Labels: links

#17 Fix Markdown Italic
  source/_posts/434.md
Labels: enhancement

#18 Try 2 fix get hostname while making
  Makefile
Labels: bug
